# Generated by Django 4.2.3 on 2023-07-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_order_remove_transaction_name_alter_transaction_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_cancelled',
            new_name='is_canceled',
        ),
    ]
