# Generated by Django 4.2.3 on 2023-07-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_is_cancelled_order_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
